apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.name }}-service
  labels:
    app: {{ .Values.client.name }}
spec:
  ports:
  - port: 12345 # //TODO
    protocol: TCP
    targetPort: 12345 # //TODO
  selector:
    app: {{ .Values.client.name }}
  type: LoadBalancer
