apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}-service
  labels:
    app: {{ .Values.server.name }}
spec:
  ports:
  - port: {{ .Values.server.port }}
    protocol: TCP
    targetPort: {{ .Values.server.port }}
  selector:
    app: {{ .Values.server.name }}
  type: LoadBalancer
