environment: development
client:
  name: client
  image: localhost:5100/log-client
  tag: latest
  replicas: 1
server:
  name: server
  port: 80
  image: localhost:5100/log-server
  tag: latest
  replicas: 3
env:
  otel_exporter_jaeger_endpoint: http://jaeger:14268/api/traces
  speed_cof: 200
